apiVersion: v1
kind: ReplicationController
metadata:
  name: crate
  labels:
    provider: crate
    heritage: helm
spec:
  replicas: 1
  selector:
    provider: crate
  template:
    metadata:
      name: crate
      labels:
        provider: crate
    spec:
      containers:
      - name: crate
        image: crate
        volumeMounts:
        - mountPath: /data
          name: crate-data
        ports:
        - containerPort: 4200
        - containerPort: 4300
    volumes:
    - name: crate-data
      emptyDir: {}
